# More option see https://github.com/DreamMaoMao/mango/wiki/
exec=killall -SIGUSR2 waybar
exec-once=sleep 1 && waybar -c ~/.config/waybar/mango-config.jsonc
exec-once=~/projects/scripts/mango-columns-watcher.sh
exec-once=~/projects/scripts/battery-warner.sh
exec-once=dunst
exec-once=nm-applet
exec-once=blueman-applet 
exec-once=swaybg -m fill -i /usr/share/backgrounds/clown.jpeg
exec-once=fcitx5 -dr
exec-once=wl-paste --type text --watch cliphist store

env=XCURSOR_THEME,LyraQ-cursors
env=TERMINAL,foot
env=GDK_SCALE,1
env=GDK_DPI_SCALE,1
env=EDITOR,nvim
env=VISUAL,nvim
env=XDG_CACHE_HOME,/home/zaater/.local/cache
env=XDG_DATA_HOME,/home/zaater/.local/share
env=XDG_CONFIG_HOME,/home/zaater/.config
env=XDG_STATE_HOME,/home/zaater/.local/state
env=GTK_IM_MODULE,fcitx
env=QT_IM_MODULES,wayland;fcitx
env=XMODIFIERS,@im=citx
env=QT_QPA_PLATFORMTHEME,qt6ct

# layout support:
# tile,scroller,grid,deck,monocle,center_tile,vertical_tile,vertical_scroller
tagrule=id:1,layout_name:tile
tagrule=id:2,layout_name:monocle
tagrule=id:3,layout_name:tile
tagrule=id:4,layout_name:tile
tagrule=id:5,layout_name:tile
tagrule=id:6,layout_name:tile
tagrule=id:7,layout_name:tile
tagrule=id:8,layout_name:tile
tagrule=id:9,layout_name:tile

# layer rule
# layerrule=animation_type_open:zoom,layer_name:rofi
# layerrule=animation_type_close:zoom,layer_name:rofi

source=./bind.conf
source=./opts.conf
source=./rule.conf

switchbind=fold,spawn,swaylock

# vim: ft=hyprlang
